      SUBROUTINE HADLO123(IMASS,Isch,Ihad,IPARTIN,XBJ,Q,F1M,F2M,
     >   GLQ1,GRQ1,GLQ2,GRQ2,XMU,ISET,HMASS,XLO123)
      Implicit Double Precision (A-H, O-Z)
      Dimension XLO123(3), XLOLR(-1:1)

       CALL HADLO(IMASS,Isch,Ihad,IPARTIN,XBJ,Q,F1M,F2M,
     >   GLQ1,GRQ1,GLQ2,GRQ2,XMU,ISET,HMASS,XLOLR)
       CALL HEL2TEN(XBJ,Q,HMASS,XLOLR,XLO123)

      RETURN
      END
