      SUBROUTINE  HADSUB123(IMASS,Isch,Ihad,IPARTIN,XBJ,Q,F1M,F2M,
     >   GLQ1,GRQ1,GLQ2,GRQ2,XMU,ISET,HMASS,XSUB123)
      Implicit Double Precision (A-H, O-Z)
      Dimension XSUB123( 3), XSUBLR( -1:1)

       CALL HADSUB(IMASS,Isch,Ihad,IPARTIN,XBJ,Q,F1M,F2M,
     >   GLQ1,GRQ1,GLQ2,GRQ2,XMU,ISET,HMASS,XSUBLR)
       CALL HEL2TEN(XBJ,Q,HMASS,XSUBLR,XSUB123)

      RETURN
      END
